export default {
  전체: "",
  서울: "magenta",
  경기: "lime",
  인천: "volcano",
  강원: "orange",
  세종: "cyan",
  충북: "gold",
  충남: "green",
  경북: "red",
  경남: "#FDAFAB",
  대구: "#FAD4AE",
  부산: "#FFAFB0",
  울산: "#F0CC96",
  대전: "#108ee9",
  전북: "blue",
  전남: "geekblue",
  광주: "#6EA8C9",
  제주: "purple",
};
